### ISSUE TITLE
LSP Doesn't appear to respect some grammar types.

### ISSUE THREAD

**Issue by rwatts3** [atom/atom-languageclient#75]
Attempting to get `ide-typescript` working in html script blocks.
I've added `source.js.embedded.html` to the getGrammarScopes() method, and intellisense nothing happens even with debug LSP active.

**Comment by rwatts3** [comment]
any suggestions ?

**Comment by damieng** [comment]
It's possible this is related to one of the other open grammar issues that should be fixed today or tomorrow.

**Comment by damieng** [comment]
Let me know if the 0.1.4 update solves this problem for you, if not I'll re-open this and we can try some more debugging steps.

**Comment by rwatts3** [comment]
Hello @damieng 
That didn't seem to fix the problem. 
The intellisense doesn't show when editing a script block within an html file. 

I had a few thoughts after this task is complete.

1. Add a configuration option to `ide-typescript` That allows us to pass a comma delimited list of grammar scopes.
2. In `ide-typescript` lib/main.js we should then be able to check and parse that list, then push them to an array. 
3. Update the grammarScopes array to use the array mentioned in step 2. 

Leverages modularity, and allows any grammar scope to be dynamically registered to the extension. 
But first we should at least get `source.js.embedded.html`  as one of the predefined scopes.

**Comment by damieng** [comment]
Yeah embedded blocks within a file definitely aren't going to work right now.  The LSP is very file based and our design right now also reflects that.

At a minimum we'd need to change our scope-checking logic to look through the whole opened file scopes to see if there are any matching sub-grammar blocks rather than just looking at the root one.

I don't think we need scope overrides if we go down that route although I'd still like to add them as a per-package config override.
